version: "3.7"
services:
  app:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    links:
      - db
    depends_on:
      - db
    networks:
      - app-db
      - app-nginx

  db:
    image: mariadb
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: user_system
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: test
      MYSQL_USER: test
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
    networks:
      - app-db
      - phpmyadmin-nginx
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=laravel-db
      - PMA_USER=root
      - PMA_PASSWORD=root
    volumes:
      - ./phpmyadmin/sessions:/sessions
    ports:
      - 8000:80
    links:
      - db
      - nginx
    depends_on:
      - db
      - nginx
    networks:
      - db-phpmyadmin
      - phpmyadmin-nginx


  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      # Uncomment the code if you want to see logs.
      # - ./nginx/:/var/log/nginx/
#    When you want add ports
    # extra_hosts:
      # - test.com:127.0.0.2
    links:
      - app
    depends_on:
      - app
    networks:
      - app-nginx
      - phpmyadmin-nginx

networks:
  app-db:
    driver: bridge
  app-nginx:
    driver: bridge
  db-phpmyadmin:
    driver: bridge
  phpmyadmin-nginx:
    driver: bridge
